# Generated by Django 3.1 on 2021-08-02 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import uuid
import validation.image_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article_thumbnail/', validators=[validation.image_validators.image_validator], verbose_name='サムネイル')),
                ('encoded_thumbnail', models.TextField(blank=True, null=True, verbose_name='エンコードしたサムネイル')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('summary', models.TextField(verbose_name='前書き')),
                ('body', models.TextField(verbose_name='本文')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='筆者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
